- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Uninstall nginx
    service:
      name: nginx
      state: stopped
  - name: ensure nginx is not installed
    apt: 
      name: nginx 
      state: absent
      autoremove: yes