- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
    register: cache_var
    failed_when: "'cache_update_time' < 1"

  - name: check cache
    debug:
      msg: heres the output {{ cache_var }}

  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config

  # - name: create dir to cause failure
  #   command: mkdir /etc/nginx/
  #   register: mkdir_output_var
  #   failed_when: "'File exists' not in mkdir_output_var.stderr and mkdir_output_var.rc !=0"
  # - name: Output from debug
  #   debug:
  #     msg: Here is output for nginx_conf - {{ nginx_config }}

  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true